//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SKU
    {
        public string client_name { get; set; }
        public string SKU1 { get; set; }
        public string description { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> width { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> rate { get; set; }
        public string supplier { get; set; }
        public Nullable<decimal> cost { get; set; }
        public string category { get; set; }
        public string notes { get; set; }
        public string image_url { get; set; }
    
        public virtual tbl_client tbl_client { get; set; }
    }
}
