//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class tbl_asn
    {
        public string client_name { get; set; }
        public Nullable<System.DateTime> arr_date { get; set; }
        public string notes { get; set; }
        public int order { get; set; }
        [ForeignKey("client_name")]
        public  tbl_client tbl_client { get; set; }
    }
}
