//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_client()
        {
            this.SKUs = new HashSet<SKU>();
            this.tbl_asn = new HashSet<tbl_asn>();
        }
    
        public string client_name { get; set; }
        public string contact_person { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string consumer_email { get; set; }
        public string claim_email { get; set; }
        public string fax { get; set; }
        public string add_1 { get; set; }
        public string add_2 { get; set; }
        public string city { get; set; }
        public string province { get; set; }
        public string country { get; set; }
        public Nullable<int> zip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SKU> SKUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_asn> tbl_asn { get; set; }
    }
}
